baseURL = 'https://akihama-00.github.io/my-blog/'
languageCode = 'ja-jp'
title = 'ğŸ HOMEğŸ '
theme = 'PaperMod'
defaultContentLanguage = "ja"
timeZone = "Asia/Tokyo"
googleAnalytics = "G-P9201X7CLY"


[[menu.main]]
  identifier = "posts"
  name = "âœ’ï¸æŠ•ç¨¿"
  url = "/posts/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "ğŸ’¼çµŒæ­´"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "search"
  name = "ğŸ”æ¤œç´¢"
  url = "/search/"
  weight = 3

[params]
  ShowBreadCrumbs = true # ãƒ‘ãƒ³ããšãƒªã‚¹ãƒˆï¼ˆä¸Šéƒ¨ã®éšå±¤è¡¨ç¤ºï¼‰ã‚’è¡¨ç¤º
  ShowCodeCopyButtons = true # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã«ã‚³ãƒ”ãƒ¼ç”¨ã®ãƒœã‚¿ãƒ³ã‚’è¡¨ç¤º
  ShowPostNavLinks = true # è¨˜äº‹ä¸‹ã«ã€Œå‰/æ¬¡ã®è¨˜äº‹ãƒªãƒ³ã‚¯ã€ã‚’è¡¨ç¤º
  ShowReadingTime = true # èª­äº†ç›®å®‰æ™‚é–“ï¼ˆ3åˆ†ã§èª­ã‚ã¾ã™ï¼‰ãªã©ã‚’è¡¨ç¤º
  ShowToc = true # è¨˜äº‹ã®ç›®æ¬¡ï¼ˆTable of Contentsï¼‰ã‚’è¡¨ç¤ºãƒ»å±•é–‹
  TocOpen = true # ä¸ŠåŒæ§˜
  showShareButtons = true # ã‚½ãƒ¼ã‚·ãƒ£ãƒ«å…±æœ‰ãƒœã‚¿ãƒ³
  UseHugoToc = true # Hugoæ¨™æº–ã®ç›®æ¬¡æ©Ÿèƒ½ã‚’ä½¿ã†ã‹ã©ã†ã‹
  ShowPostCover = true # è¨˜äº‹ã”ã¨ã«ã‚«ãƒãƒ¼ç”»åƒï¼ˆã‚¢ã‚¤ã‚­ãƒ£ãƒƒãƒï¼‰ã‚’è¡¨ç¤º
  ShowPageTitleInHome = true # ã‚µã‚¤ãƒˆå…¨ä½“ã®ãƒ‡ã‚¶ã‚¤ãƒ³ãƒ¢ãƒ¼ãƒ‰ï¼ˆauto, light, darkï¼‰
  socialIcons = [
    { name = "github", url = "https://github.com/Akihama-00" },
    { name = "x", url = "https://x.com/AkhBlog" }
  ]
  env = "production"

[params.assets]
  favicon = "favicon.ico"
  customCSS = ["css/custom.css"]  # â† ã‚«ã‚¹ã‚¿ãƒ ãƒ‡ã‚¶ã‚¤ãƒ³ã—ãŸã„ã¨ãã«ä½¿ã„ã¾ã™

[outputs]
  home = ["HTML", "JSON"]

[params.profileMode]
enabled = true
title = "ã“ã‚“ã«ã¡ã¯ã€Akihamaã§ã™ï¼"
subtitle = "ã‚·ã‚¹ãƒ†ãƒ ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã¨ã—ã¦ã€æ—¥ã€…æˆé•·ä¸­ã€‚"
imageUrl = "images/cat-sunglasses.jpg"
imageTitle = "ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«ç”»åƒ"
imageWidth = 120
imageHeight = 120

